version: "3.9"

services:
  api:
    image: julbetan/api_deportes:latest
    container_name: api_deportes
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=.prod_env
    depends_on:
      - db
    restart: always

  frontend:
    image: julbetan/frontend_kingtide:latest
    container_name: frontend_kingtide
    ports:
      - "5173:5173"
    restart: always

  db:
    image: postgres:alpine
    container_name: deportes-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - /root/projects/king_tide/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
