version: "3.9"

services:
  api:
    image: julbetan/api_deportes:latest
    container_name: api_deportes
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - db
    restart: always

  frontend:
    image: julbetan/frontend_kingtide:latest
    container_name: frontend_kingtide
    ports:
      - "80:80"
    restart: always

  db:
    image: postgres:alpine
    container_name: deportes-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - /root/projects/king_tide/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  clima:
    image: julbetan/api_clima:latest
    container_name: api_clima
    ports:
      - "3000:3000"
    restart: always
  
  scheduler:
    image: julbetan/update_events_scheduler:latest
    container_name: update_events_scheduler
    restart: always
