name: Deploy Scheduler

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile.scheduler -t julbetan/update_events_scheduler:latest .
          docker push julbetan/update_events_scheduler:latest

      - name: Deploy scheduler to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/projects/king_tide/deploy_kingtide
            docker-compose -f docker-compose.prod.yml pull scheduler
            docker-compose -f docker-compose.prod.yml up -d --remove-orphans scheduler
